### ISSUE TITLE
VoodooHdaSettingsLoader dose not work 

### ISSUE THREAD

**Issue by zengxiaoliang** [chris1111/VoodooHDA-2.9.2-Clover-V14#9]
OS: 10.13.6 (17G2112)
appVersion: VoodooHDA-2.9.2-Clover-V14

issue:
start VoodooHdaSettingsLoader failed （same as root）

exception ： 2019-12-09 18:07:37.809 VoodooHdaSettingsLoader[655:7069] Couldn't load settings file (file opening problem: not here, or read protected)

**Comment by chris1111** [comment]
VoodooHdaSettingsLoader is useless anyway, it was introduced in the old VoooDoo Installer but not adapt to the new VodooHDA 
You can delete it I will remove in the next release
